### ISSUE TITLE
Problem in installing files

### ISSUE THREAD

**Issue by RahmatAliMalik5** [darklektor/ASP.NET-Identity-SQLite-EntityFramework#2]
I am not able to install **sqlite-netFx46-setup-bundle-x64-2015-1.0.105.2.exe** file. My .Net Framework is 4.6.1. But when I install it it opens a command line window and run compilation which shows errors.
![error](https://user-images.githubusercontent.com/31620469/32158154-39bfd27e-bd69-11e7-99e3-46b12d7e30e8.PNG)
. I am going to attach SQLite with my ASP.NET MVC 5 app. Can you suggest me some kind of helping material for it?

**Comment by ghost** [comment]
@RahmatAliMalik5 Have you read my installation guide? Are you running x64 OS?

**Comment by RahmatAliMalik5** [comment]
I am using Windows 10. But Man! my problem is solved now. How that happened I don't know about. But my problem is solved. A lot of thanks for replying to my comment.
